const fs=require('fs'),assert=require('assert');
const gs=fs.readFileSync('V2.GS.txt','utf8');
const save=gs.slice(gs.indexOf('function שמירת_משימה(data)'),gs.indexOf('function מחיקת_משימה',gs.indexOf('function שמירת_משימה(data)')));
assert(save.includes('row["כניסה ליומן"] === "כן" && row["תאריך"] && row["שעה"]'),'calendar-eligible save is gated by the calendar flag and schedule');
assert(save.includes('syncCalendarEvent_(row, { includeGuests: false, sendUpdates: "none" })'),'save syncs the event without guests or notifications');
assert(save.indexOf('syncCalendarEvent_') < save.indexOf('upsert_ללא_אימות_'),'event id is returned into the canonical row before persistence');
assert(!save.includes('Calendar.Events.delete'),'changing the flag to no preserves the historical event');
const invite=gs.slice(gs.indexOf('function שליחת_זימון_יומן_למשימה_Build11'),gs.indexOf('function יצירת_משתמש_חדש_Build11',gs.indexOf('function שליחת_זימון_יומן_למשימה_Build11')));
assert(invite.includes('includeGuests: true, sendUpdates: "all"'),'dedicated invitation action syncs guests and sends updates');
const sync=gs.slice(gs.indexOf('function BH_calendarEventResource_'),gs.indexOf('/***********************',gs.indexOf('function BH_calendarEventResource_')));
assert(sync.includes('if (includeGuests === true) resource.attendees = guests'),'shared resource builder only attaches guests explicitly');
assert(sync.includes('options.sendUpdates || "none"'),'event sync defaults to no notifications');
const create=fs.readFileSync('tests/create_local_patch_runtime_test.js','utf8');
assert(create.includes("route:'task-create-canonical-v1'"),'CREATE local-patch regression coverage remains present');
console.log('calendar save/invitation semantics assertions passed');
