const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'), gs=fs.readFileSync('V2.GS.txt','utf8');
const block=html.match(/<script id="BH_CREATE_LOCAL_PATCH_BUILD17">([\s\S]*?)<\/script>/)[1];
assert(/goDashboard\s*=\s*function\(\)[\s\S]*tab\('dashboard'/.test(block));
assert(!/goDashboard\s*=\s*function\(\)[\s\S]{0,150}(hardRefresh|load\(|refreshCore\()/.test(block));
for(const entity of ['task','contact','project']) assert(block.includes("runCreate('"+entity+"'"));
assert(block.includes('if(fellBack) return'));
assert(block.includes('if(pending[entity]) return'));
assert(block.includes('CRM_MUTATION_PERF'));
for(const route of ['שמירת_משימה_חדשה_קנונית_Build17','שמירת_איש_קשר_חדש_קנונית_Build17','שמירת_פרויקט_חדש_קנונית_Build17']) assert(gs.includes('function '+route));
assert(gs.includes('response.record["הרשאת מערכת"]'));
const build17=gs.slice(gs.indexOf('Build 17 – canonical CREATE'),gs.indexOf('var BH_DIAG_originalSaveContact_',gs.indexOf('Build 17 – canonical CREATE')));
assert(!/קבלת_נתוני_ליבה_Build13|קבלת_נתוני_מערכת_מלאים_Build10_|refreshCore/.test(build17));
assert(gs.includes('out.calendarCreatorsAdded'));
assert(gs.includes('out.affectedLinks = []'));
assert(gs.includes('BH_createDashboardPatch_Build17_'));
console.log('create local patch static test passed');
