const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'), gs=fs.readFileSync('V2.GS.txt','utf8');
function has(src,re,msg){assert(re.test(src),msg);}
has(html,/CRM_FAST_SHELL_DEFAULT_MODE = 'privileged'/,'safe privileged rollout flag exists');
has(html,/function CRM_fastShellEnabled_\(\)\{ return CRM_fastShellMode_\(\) !== 'off'; \}/,'missing or stale cached role cannot choose the route');
const decision=html.slice(html.indexOf('function CRM_fastShellMode_'),html.indexOf('function CRM_fastShellPayloadValid_'));
assert(!/localStorage|CRM_USER_INFO|\.role|isOwner/.test(decision),'client rollout decision does not trust cached identity');
has(html,/if\(!CRM_fastShellEnabled_\(\)\)\{ CRM_loadFullCoreFallback_[^\n]*false\); return;/,'mode off selects full core directly');
has(html,/\.קבלת_נתוני_פתיחה_Build13_2\(token,perf\.requestId,CRM_fastShellMode_\(\)\)/,'new browser calls opening endpoint with one request');
has(html,/withFailureHandler\(e=>CRM_loadFullCoreFallback_/,'transport failure falls back once');
has(html,/if\(!CRM_fastShellPayloadValid_\(d\)\)\{ CRM_loadFullCoreFallback_/,'invalid schema falls back once');
has(html,/if\(isFastShell\) renderShell_Build13_2\(DATA\); else render\(DATA\);/,'opening success bypasses the effective full render wrapper chain');
has(html,/if\(d && d\.payloadType === 'fullCore'/,'server-owned rollout can return old mode in same request');
has(html,/schemaVersion === 1[\s\S]*loadedModules\.dashboard === true/,'opening schema validates dashboard-only state');
const shell=gs.slice(gs.indexOf('function BH_FAST_shellForPrivilegedUser_'),gs.indexOf('// The client supplies only a rollout preference'));
assert(!/readSheet_|קבלת_נתוני_מערכת_מלאים_Build10_/.test(shell),'privileged shell never builds or reads full core collections');
assert(!/SHEETS\.LINKS|SHEETS\.SETTINGS|הגדרות_שדות|קבלת_הרשאות/.test(shell),'shell omits links/settings/fields/raw permissions');
has(shell,/BH_FAST_activeSummary_\(SHEETS\.PROJECTS,true\)/,'projects use archive projection and five dashboard rows');
has(shell,/BH_FAST_activeSummary_\(SHEETS\.CONTACTS,false\)/,'contacts use count projection only');
has(shell,/BH_FAST_taskSummary_\(\)/,'tasks use date/archive projection and selected full rows');
has(gs,/function BH_FAST_trackRangeRead_/,'targeted read instrumentation exists');
has(gs,/__BH_REQUEST_PERF__\.readDurations/,'targeted reads report duration');
has(gs,/__BH_REQUEST_PERF__\.sheetRowsRead/,'targeted reads report row counts');
has(gs,/const eligible=user\.isOwner===true\|\|role==='מנהל ראשי'\|\|\(forced&&role==='לקוח'\)/,'server owns eligibility; mode on cannot elevate ordinary roles');
has(gs,/role==='לקוח'\?BH13_4_applyCustomerDomainIfNeeded_/,'customer fast mode preserves server domain gate/filtering');
has(html,/if\(__BH_LOADED_MODULES__\[module\]\)[\s\S]*renderModule_Build13_2\(module\);[\s\S]*return;/,'loaded modules are requested once');
const finalOpening=gs.slice(gs.lastIndexOf('קבלת_נתוני_פתיחה_Build13_2=function'),gs.indexOf('function BH_FAST_moduleForAuthorizedUser_',gs.lastIndexOf('קבלת_נתוני_פתיחה_Build13_2=function')));
assert(!/קבלת_נתוני_ליבה_Build13\(/.test(finalOpening),'successful shell never invokes public full core route');
for(const metric of ['fastShell.serverRoundTrip','fastShell.total','fastShell.payloadBytes','fastShell.recordsReturned','fastShell.sheetReads','fastShell.firstDataRender','fullCoreFallback','timeToDashboardUsable']) has(html,new RegExp(metric.replaceAll('.','\\.')),metric+' metric exists');
console.log('fast opening shell assertions passed');
