const fs = require('fs');
const assert = require('assert');
const html = fs.readFileSync('index.html', 'utf8');
const gs = fs.readFileSync('V2.GS.txt', 'utf8');
const statusPatchMatch = /<script id="BH_TASK_STATUS_PATCH">([\s\S]*?)<\/script>/.exec(html);
const statusPatch = statusPatchMatch ? statusPatchMatch[1] : '';

function has(re, message){ assert(re.test(html), message); }
has(/if\(!id\)\{[\s\S]*?refreshCore[\s\S]*?return;[\s\S]*?BH_saveTaskEditLocal\(id, request\)/, 'only create retains full refresh; edit uses local route');
has(/applyDecision\(DATA\.tasks, response\.taskDecision, response\.canonicalTask/, 'server task decision drives the task collection');
has(/applyDecision\(DATA\.calendarTasks, response\.calendarDecision, response\.canonicalCalendarRecord/, 'server calendar decision drives the calendar collection');
has(/DATA\.calendarCreatorsAllowed = response\.calendarCreatorsAllowed\.slice\(\)/, 'canonical creator list replaces local derived state');
has(/DATA\.dashboard = response\.dashboard/, 'canonical dashboard replaces stale buckets');
has(/tableTasks\(\);[\s\S]*?renderDashboard\(\);[\s\S]*?renderCalendarDashboard[\s\S]*?renderTaskCard/, 'task-dependent views render');
has(/pending\[key\]\) return false/, 'duplicate in-flight edit is blocked');
has(/state\.sequence < \(latestApplied\[key\] \|\| 0\)/, 'late response cannot overwrite a newer result');
has(/finally\{ delete pending\[key\]; clearBusy\(\); \}/, 'success and patch failures clear pending and central busy state');
has(/withFailureHandler[\s\S]*?delete pending\[key\];[\s\S]*?clearBusy\(\)/, 'transport failure clears pending and central busy state');
has(/if\(state\.fallback\) return;[\s\S]*?refreshCore/, 'fallback is single-shot');
has(/sessionExpired\(error\)[\s\S]*?canonicalLogout[\s\S]*?return;[\s\S]*?fallbackOnce/, 'session expiry logs out and never falls into refresh');
has(/console\.info\('CRM_MUTATION_PERF'/, 'safe focused instrumentation exists');
assert(!/function BH_saveTaskEditLocal[\s\S]*?tableProjects\(\)/.test(html), 'project view is not rendered by local patch');
assert(!/function BH_saveTaskEditLocal[\s\S]*?tableContacts\(\)/.test(html), 'contact view is not rendered by local patch');
assert(/const canonicalCore = קבלת_נתוני_ליבה_Build13\(data\.authToken\)/.test(gs), 'server reuses the effective Full Core pipeline');
assert(/taskDecision: taskVisible \? \(taskWasPresent \? "replace" : "insert"\) : "remove"/.test(gs), 'server decides task membership');
assert(/calendarDecision: calendarVisible \? \(calendarWasPresent \? "replace" : "insert"\) : "remove"/.test(gs), 'server decides calendar membership');
assert(/canonicalCalendarRecord: canonicalCalendarRecord/.test(gs), 'server returns enriched canonical calendar record');
assert(/calendarCreatorsAllowed: \(canonicalCore\.calendarCreatorsAllowed/.test(gs), 'server returns canonical creator list');
assert(/sequence: Number\(data\.clientSequence/.test(gs), 'contract echoes sequence');
assert(/fullInvalidation:true/.test(gs), 'uncertain canonical core contract forces full invalidation');
assert(statusPatch, 'effective Done/Reactivate local patch exists');
assert(/window\.doneTask\s*=.*mutateStatus/.test(statusPatch), 'done uses the effective local patch route');
assert(/window\.reactivateTask\s*=.*mutateStatus/.test(statusPatch), 'reactivate uses the effective local patch route');
assert(/if\(patched\)[\s\S]*?return;[\s\S]*?fallback\(/.test(statusPatch), 'Done/Reactivate refresh only after a rejected local patch');
const afterStatusPatch = html.slice(statusPatchMatch.index + statusPatchMatch[0].length);
assert(!/(?:window\.)?doneTask\s*=|function\s+doneTask\s*\(/.test(afterStatusPatch), 'no later done override restores full refresh');
assert(!/(?:window\.)?reactivateTask\s*=|function\s+reactivateTask\s*\(/.test(afterStatusPatch), 'no later reactivate override restores full refresh');
assert(!/\.github\/workflows/.test(require('child_process').execSync('git diff --name-only').toString()), 'workflow files are unchanged');
console.log('task_edit_local_patch_test: OK');
